### ISSUE TITLE
Creating fail2ban.conf fails with NoMethodError

### ISSUE THREAD

**Issue by wndhydrnt** [chef-cookbooks/fail2ban#51]
### Cookbook version
5.0.0

### Chef-client version
12.7.2

### Platform Details
CentOS 7.2 via Kitchen
```
$ ohai --version
Ohai: 8.10.0
```

### Scenario:
Installing fail2ban via the `default` recipe.

### Steps to Reproduce:
I'm using the following .kitchen.yml file:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.7.2

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[fail2ban::default]
    attributes:
```
and execute `kitchen converge`.

### Expected Result:
fail2ban is installed.

### Actual Result:
chef-client throws an error:

```
Recipe: fail2ban::default
 * yum_package[fail2ban] action install
   - install version 0.9.7-1.el7 of package fail2ban
 * ohai[reload package list] action reload
   - re-run ohai and merge results into node attributes
 * ohai[reload package list] action nothing (skipped due to action :nothing)
 * template[/etc/fail2ban/fail2ban.conf] action create

   ================================================================================
   Error executing action `create` on resource 'template[/etc/fail2ban/fail2ban.conf]'
   ================================================================================

   NoMethodError
   -------------
   undefined method `[]' for nil:NilClass

   Cookbook Trace:
   ---------------
   /tmp/kitchen/cookbooks/fail2ban/recipes/default.rb:46:in `block (2 levels) in from_file'
   /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/property.rb:11:in `get'
   /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/mixin/params_validate.rb:11:in `get'
   /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
   /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
   /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
   /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
   /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

   Resource Declaration:
   ---------------------
   # In /tmp/kitchen/cookbooks/fail2ban/recipes/default.rb

    41: template '/etc/fail2ban/fail2ban.conf' do
    42:   source 'fail2ban.conf.erb'
    43:   owner 'root'
    44:   group 'root'
    45:   mode '0644'
    46:   variables(lazy { { f2b_version: node['packages']['fail2ban']['version'].match(/^[0-9]+\.[0-9]+/)[0].to_f } })
    47:   notifies :restart, 'service[fail2ban]'
    48: end
    49:

   Compiled Resource:
   ------------------
   # Declared in /tmp/kitchen/cookbooks/fail2ban/recipes/default.rb:41:in `from_file'

   template("/etc/fail2ban/fail2ban.conf") do
     action [:create]
     retries 0
     retry_delay 2
     default_guard_interpreter :default
     source "fail2ban.conf.erb"
     variables #<Chef::DelayedEvaluator:0x00000003d85e98@/tmp/kitchen/cookbooks/fail2ban/recipes/default.rb:46>
     declared_type :template
     cookbook_name :fail2ban
     recipe_name "default"
     owner "root"
     group "root"
     mode "0644"
     atomic_update true
     path "/etc/fail2ban/fail2ban.conf"
   end


Running handlers:
[2018-02-15T08:52:36+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-02-15T08:52:36+00:00] ERROR: Exception handlers complete
Chef Client failed. 7 resources updated in 21 seconds
[2018-02-15T08:52:36+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2018-02-15T08:52:36+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-02-15T08:52:36+00:00] ERROR: template[/etc/fail2ban/fail2ban.conf] (fail2ban::default line 41) had an error: NoMethodError: undefined method `[]' for nil:NilClass
[2018-02-15T08:52:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I've added the kitchen config file to make it easier for you to reproduce the issue. We are also seeing the same error on our servers.

**Comment by tas50** [comment]
I'm fairly certain you're running into this issue since you lack the packages plugin the cookbook now uses. You'll need to update to a newer Chef 12 release (or ideally Chef 13). Chef 12 goes EOL in April and the release you're running is several years old. I've pushed a 5.0.1 version of this cookbook with an updated chef client requirement in the readme/metadata.
